# Generated by Django 5.2 on 2025-04-05 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_post_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
